# Generated by Django 5.2.6 on 2025-09-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="c.pokf@1", max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
