# Generated by Django 5.2.6 on 2025-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_student_address_student_email_alter_student_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=500)),
                ("speed", models.IntegerField(default=50)),
            ],
        ),
    ]
